# Generated by Django 4.2.7 on 2025-06-14 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del dashboard')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_default', models.BooleanField(default=False, verbose_name='Dashboard por defecto')),
                ('is_public', models.BooleanField(default=False, verbose_name='Dashboard público')),
                ('layout', models.JSONField(default=dict, verbose_name='Configuración de layout')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del KPI')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('category', models.CharField(choices=[('SALES', 'Ventas'), ('INVENTORY', 'Inventario'), ('FINANCIAL', 'Financiero'), ('OPERATIONAL', 'Operacional'), ('CUSTOMER', 'Clientes')], max_length=20, verbose_name='Categoría')),
                ('formula', models.TextField(verbose_name='Fórmula o cálculo')),
                ('unit', models.CharField(max_length=20, verbose_name='Unidad de medida')),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor objetivo')),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor actual')),
                ('previous_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor anterior')),
                ('trend', models.CharField(choices=[('UP', 'Ascendente'), ('DOWN', 'Descendente'), ('STABLE', 'Estable')], default='STABLE', max_length=10, verbose_name='Tendencia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('update_frequency', models.CharField(choices=[('REALTIME', 'Tiempo Real'), ('HOURLY', 'Cada Hora'), ('DAILY', 'Diario'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensual')], default='DAILY', max_length=20, verbose_name='Frecuencia de actualización')),
                ('last_calculated', models.DateTimeField(blank=True, null=True, verbose_name='Última actualización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPIs',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('widget_type', models.CharField(choices=[('CHART_LINE', 'Gráfico de Líneas'), ('CHART_BAR', 'Gráfico de Barras'), ('CHART_PIE', 'Gráfico Circular'), ('METRIC', 'Métrica Simple'), ('TABLE', 'Tabla'), ('HEATMAP', 'Mapa de Calor'), ('GAUGE', 'Indicador')], max_length=20, verbose_name='Tipo de widget')),
                ('data_source', models.CharField(choices=[('SALES', 'Ventas'), ('INVENTORY', 'Inventario'), ('PREDICTIONS', 'Predicciones'), ('CUSTOMERS', 'Clientes'), ('PRODUCTS', 'Productos')], max_length=20, verbose_name='Fuente de datos')),
                ('query_config', models.JSONField(default=dict, verbose_name='Configuración de consulta')),
                ('display_config', models.JSONField(default=dict, verbose_name='Configuración de visualización')),
                ('position_x', models.IntegerField(default=0, verbose_name='Posición X')),
                ('position_y', models.IntegerField(default=0, verbose_name='Posición Y')),
                ('width', models.IntegerField(default=4, verbose_name='Ancho')),
                ('height', models.IntegerField(default=4, verbose_name='Alto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('refresh_interval', models.IntegerField(default=300, verbose_name='Intervalo de actualización (segundos)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='analytics.dashboard', verbose_name='Dashboard')),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
                'ordering': ['dashboard', 'position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del reporte')),
                ('report_type', models.CharField(choices=[('SALES', 'Reporte de Ventas'), ('INVENTORY', 'Reporte de Inventario'), ('PREDICTION', 'Reporte de Predicciones'), ('PERFORMANCE', 'Reporte de Rendimiento'), ('FINANCIAL', 'Reporte Financiero'), ('CUSTOMER', 'Reporte de Clientes')], max_length=20, verbose_name='Tipo de reporte')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('start_date', models.DateField(verbose_name='Fecha inicio')),
                ('end_date', models.DateField(verbose_name='Fecha fin')),
                ('file_format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV'), ('JSON', 'JSON')], max_length=10, verbose_name='Formato')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Archivo')),
                ('filters', models.JSONField(default=dict, verbose_name='Filtros aplicados')),
                ('parameters', models.JSONField(default=dict, verbose_name='Parámetros')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de generación')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Stock Bajo'), ('OVERSTOCK', 'Sobrestock'), ('EXPIRATION', 'Producto por Vencer'), ('PREDICTION', 'Alerta de Predicción'), ('SALES_TARGET', 'Meta de Ventas'), ('SYSTEM', 'Alerta del Sistema')], max_length=20, verbose_name='Tipo de alerta')),
                ('severity', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('CRITICAL', 'Crítico')], max_length=10, verbose_name='Severidad')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leído')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resuelto')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('data', models.JSONField(default=dict, verbose_name='Datos adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Producto')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Resuelto por')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-created_at'],
            },
        ),
    ]
